spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dry_cleaning
    username: postgres
    password: Qwerty2411.
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate